name: Build, push and deploy Fpsak-frontend

on:
  push:
    branches:
      - forberede-azure-ad-login
env:
  CLUSTER: "dev-fss"
  IMAGE_BASE: ghcr.io/navikt/fp-frontend-azure
  SHOULD_DEPLOY: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Sjekk ut kode
        uses: actions/checkout@v2.3.4
      - run: git fetch --prune --unshallow
      - id: tag
        run: |
          echo '::set-output name=TAG::'$(git rev-parse --short HEAD)

      - name: Sette opp Node
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 18.x

      - name: Get yarn cache
        id: yarn-cache
        run: |
          echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache node modules
        uses: actions/cache@v2.1.6
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Run yarn install
        run: yarn install --ignore-optional --no-progress --frozen-lockfile

      #- name: Run linting
      #  run: yarn less:lint && yarn lint && yarn ts-check

      #- name: Run test and coverage
      #  run: yarn test:coverage

      - name: Build
        run: |
          echo "IMAGE=$IMAGE_BASE:$TAG" >> $GITHUB_ENV
          yarn build

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: DockerfileAzureLogin
          push: ${{ env.SHOULD_DEPLOY }}
          tags: ${{ env.IMAGE_BASE }}:${{ steps.tag.outputs.TAG }},${{ env.IMAGE_BASE }}:latest

      - name: Deploy
        if: env.SHOULD_DEPLOY == 'true'
        uses: nais/deploy/actions/deploy@v1
        env:
          IMAGE: ${{ steps.tag.outputs.base }}:${{ steps.tag.outputs.sha }}
          CLUSTER: ${{ env.CLUSTER }}
          VARS: packages/server/dev.yaml
          RESOURCE: packages/server/naiserator.yaml
