name: Bygg og deploy fp-journalforing
on:
  workflow_dispatch:
  push:
    paths:
      - 'apps/fp-journalforing/**'
      - 'packages/**'
      - 'server/**'
      - '.deploy/fp-journalforing/**'
      - '.deploy/naiserator.yaml'
      - '.github/workflows/build-fp-journalforing.yml'
      - '.github/workflows/build.yml'
      - 'turbo.json'
      - 'Dockerfile'
      - 'yarn.lock'

jobs:
  build-app:
    name: Build
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/build.yml
    with:
      runs-on: 'ubuntu-latest'
      build-image: ${{ github.ref_name == 'master' }} # default: true
      push-image: ${{ github.ref_name == 'master' }} # default: false
      app: fp-journalforing
      image_suffix: '/fp-journalforing'
      sentry_dsn: 'https://e3fbcf06855a6a4caf8d9c8e1e92479b@sentry.gc.nav.no/185'
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN  }}

  deploy-dev:
    name: Deploy dev
    permissions:
      id-token: write
    if: github.ref_name == 'master'
    needs: build-app
    uses: navikt/fp-gha-workflows/.github/workflows/deploy.yml@main
    with:
      gar: true
      image: ${{ needs.build-app.outputs.build-version }}
      cluster: dev-gcp
      image_suffix: '/fp-journalforing'
      deploy_context: '/fp-journalforing'

  deploy-prod:
    name: Deploy prod
    permissions:
      id-token: write
    if: github.ref_name == 'master'
    needs: [build-app, deploy-dev]
    uses: navikt/fp-gha-workflows/.github/workflows/deploy.yml@main
    with:
      gar: true
      image: ${{ needs.build-app.outputs.build-version }}
      cluster: prod-gcp
      image_suffix: '/fp-journalforing'
      deploy_context: '/fp-journalforing'
