name: Bygg og deploy fp-frontend
on:
  workflow_dispatch:
  push:
    paths:
      - 'apps/fp-frontend/**'
      - 'packages/**'
      - 'server/**'
      - '.deploy/fp-frontend/**'
      - '.deploy/naiserator.yaml'
      - '.github/workflows/build-fp-frontend.yml'
      - '.github/workflows/build.yml'
      - 'Dockerfile'
      - 'yarn.lock'

jobs:
  build-app:
    name: Build
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: navikt/fp-frontend/.github/workflows/build.yml@los-app
    with:
      runs-on: 'ubuntu-latest-8-cores'
      node-version: '22.17.1'
      build-image: ${{ github.ref_name == 'los-app' }} # default: true
      push-image: ${{ github.ref_name == 'los-app' }} # default: false
      run-knip: true
      app: fp-frontend
      image_suffix: '/fp-frontend'
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN  }}

  deploy-dev:
    name: Deploy dev
    permissions:
      id-token: write
    if: github.ref_name == 'los-app'
    needs: build-app
    uses: navikt/fp-gha-workflows/.github/workflows/deploy.yml@d82a6fe449f56938a073da20baca50bed596a800
    with:
      gar: true
      image: ${{ needs.build-app.outputs.build-version }}
      cluster: dev-gcp
      image_suffix: '/fp-frontend'
      deploy_context: '/fp-frontend'

  deploy-prod:
    name: Deploy prod
    permissions:
      id-token: write
    if: github.ref_name == 'master'
    needs: [build-app, deploy-dev]
    uses: navikt/fp-gha-workflows/.github/workflows/deploy.yml@d82a6fe449f56938a073da20baca50bed596a800
    with:
      gar: true
      image: ${{ needs.build-app.outputs.build-version }}
      cluster: prod-gcp
      image_suffix: '/fp-frontend'
      deploy_context: '/fp-frontend'
